[2025-04-05T04:34:46.830+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T04:34:46.866+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.load.transform_fact_race_results scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-04-05T04:34:46.876+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.load.transform_fact_race_results scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-04-05T04:34:46.876+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-05T04:34:46.927+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load.transform_fact_race_results> on 2025-04-01 00:00:00+00:00
[2025-04-05T04:34:46.939+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'load.transform_fact_race_results', 'scheduled__2025-04-01T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/ETL_dag.py', '--cfg-path', '/tmp/tmpe4rbrr3u']
[2025-04-05T04:34:46.942+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=334) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T04:34:46.948+0000] {standard_task_runner.py:91} INFO - Job 18: Subtask load.transform_fact_race_results
[2025-04-05T04:34:46.949+0000] {standard_task_runner.py:63} INFO - Started process 354 to run task
[2025-04-05T04:34:46.998+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.load.transform_fact_race_results scheduled__2025-04-01T00:00:00+00:00 [running]> on host 0076f80062a6
[2025-04-05T04:34:47.095+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='load.transform_fact_race_results' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-01T00:00:00+00:00'
[2025-04-05T04:34:47.097+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T04:34:47.112+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T04:34:47.112+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: transform_fact_race_results() missing 1 required positional argument: 'POSTGRES_CONN_ID'
[2025-04-05T04:34:47.121+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=e_commerce_dw_etl, task_id=load.transform_fact_race_results, run_id=scheduled__2025-04-01T00:00:00+00:00, execution_date=20250401T000000, start_date=20250405T043446, end_date=20250405T043447
[2025-04-05T04:34:47.134+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 18 for task load.transform_fact_race_results (transform_fact_race_results() missing 1 required positional argument: 'POSTGRES_CONN_ID'; 354)
[2025-04-05T04:34:47.164+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-05T04:34:47.190+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-05T04:34:47.192+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-05T04:50:06.227+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T04:50:06.267+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.load.transform_fact_race_results scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-04-05T04:50:06.277+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.load.transform_fact_race_results scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-04-05T04:50:06.278+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-05T04:50:06.291+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load.transform_fact_race_results> on 2025-04-01 00:00:00+00:00
[2025-04-05T04:50:06.301+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=545) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T04:50:06.302+0000] {standard_task_runner.py:63} INFO - Started process 552 to run task
[2025-04-05T04:50:06.301+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'load.transform_fact_race_results', 'scheduled__2025-04-01T00:00:00+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/ETL_dag.py', '--cfg-path', '/tmp/tmpem6kq4wv']
[2025-04-05T04:50:06.303+0000] {standard_task_runner.py:91} INFO - Job 58: Subtask load.transform_fact_race_results
[2025-04-05T04:50:06.351+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.load.transform_fact_race_results scheduled__2025-04-01T00:00:00+00:00 [running]> on host 7b82c2aa8826
[2025-04-05T04:50:06.442+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='load.transform_fact_race_results' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-01T00:00:00+00:00'
[2025-04-05T04:50:06.444+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T04:50:06.585+0000] {logging_mixin.py:188} INFO - Các cột trong DataFrame sau khi merge:
[2025-04-05T04:50:06.586+0000] {logging_mixin.py:188} INFO - Index(['resultId', 'raceId', 'driverId', 'constructorId', 'number', 'grid',
       'position', 'positionText', 'positionOrder', 'points', 'laps', 'time_x',
       'milliseconds', 'fastestLap', 'rank', 'fastestLapTime',
       'fastestLapSpeed', 'statusId', 'year', 'round', 'circuitId', 'name',
       'date', 'time_y', 'url', 'fp1_date', 'fp1_time', 'fp2_date', 'fp2_time',
       'fp3_date', 'fp3_time', 'quali_date', 'quali_time', 'sprint_date',
       'sprint_time'],
      dtype='object')
[2025-04-05T04:50:06.697+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-05T04:50:06.730+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-05T04:50:15.381+0000] {logging_mixin.py:188} INFO - Đã transform và lưu dữ liệu vào fact_race_results
[2025-04-05T04:50:15.390+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-05T04:50:15.391+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T04:50:15.400+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=e_commerce_dw_etl, task_id=load.transform_fact_race_results, run_id=scheduled__2025-04-01T00:00:00+00:00, execution_date=20250401T000000, start_date=20250405T045006, end_date=20250405T045015
[2025-04-05T04:50:15.458+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T04:50:15.473+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-05T04:50:15.475+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
