[2025-04-08T09:27:35.522+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-08T09:27:35.649+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: formula1-etl-pipeline.transform.transform_dim_status scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-04-08T09:27:35.692+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: formula1-etl-pipeline.transform.transform_dim_status scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-04-08T09:27:35.696+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-08T09:27:35.753+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_status> on 2025-04-01 00:00:00+00:00
[2025-04-08T09:27:35.788+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'formula1-etl-pipeline', 'transform.transform_dim_status', 'scheduled__2025-04-01T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/ETL_dag.py', '--cfg-path', '/tmp/tmp7l26kt8a']
[2025-04-08T09:27:35.795+0000] {standard_task_runner.py:91} INFO - Job 32: Subtask transform.transform_dim_status
[2025-04-08T09:27:35.798+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=657) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-08T09:27:35.805+0000] {standard_task_runner.py:63} INFO - Started process 709 to run task
[2025-04-08T09:27:35.967+0000] {task_command.py:426} INFO - Running <TaskInstance: formula1-etl-pipeline.transform.transform_dim_status scheduled__2025-04-01T00:00:00+00:00 [running]> on host 1c2d39091a25
[2025-04-08T09:27:36.214+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='formula1-etl-pipeline' AIRFLOW_CTX_TASK_ID='transform.transform_dim_status' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-01T00:00:00+00:00'
[2025-04-08T09:27:36.222+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-08T09:27:36.389+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-08T09:27:36.400+0000] {logging_mixin.py:188} INFO - Đã tạo bảng thành công.
[2025-04-08T09:27:36.432+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-08T09:27:36.470+0000] {logging_mixin.py:188} INFO - Lỗi khi insert dữ liệu: duplicate key value violates unique constraint "dim_status_pkey"
DETAIL:  Key (statusid)=(1) already exists.
[2025-04-08T09:27:36.475+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-08T09:27:36.477+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/transform_dim_status.py", line 33, in transform_dim_status
    warehouse_operator.insert_table(insert_table_querry, dim_status_df)
  File "/opt/airflow/dags/postgresql_operator.py", line 35, in insert_table
    cursor.executemany(query, values)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "dim_status_pkey"
DETAIL:  Key (statusid)=(1) already exists.

[2025-04-08T09:27:36.533+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=formula1-etl-pipeline, task_id=transform.transform_dim_status, run_id=scheduled__2025-04-01T00:00:00+00:00, execution_date=20250401T000000, start_date=20250408T092735, end_date=20250408T092736
[2025-04-08T09:27:36.577+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 32 for task transform.transform_dim_status (duplicate key value violates unique constraint "dim_status_pkey"
DETAIL:  Key (statusid)=(1) already exists.
; 709)
[2025-04-08T09:27:36.638+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-08T09:27:36.671+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-08T09:27:36.676+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-08T10:10:11.478+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-08T10:10:11.524+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: formula1-etl-pipeline.transform.transform_dim_status scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-04-08T10:10:11.535+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: formula1-etl-pipeline.transform.transform_dim_status scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-04-08T10:10:11.536+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-08T10:10:11.555+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_status> on 2025-04-01 00:00:00+00:00
[2025-04-08T10:10:11.568+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'formula1-etl-pipeline', 'transform.transform_dim_status', 'scheduled__2025-04-01T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/ETL_dag.py', '--cfg-path', '/tmp/tmpzy_kwslh']
[2025-04-08T10:10:11.571+0000] {standard_task_runner.py:91} INFO - Job 18: Subtask transform.transform_dim_status
[2025-04-08T10:10:11.572+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=466) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-08T10:10:11.573+0000] {standard_task_runner.py:63} INFO - Started process 478 to run task
[2025-04-08T10:10:11.633+0000] {task_command.py:426} INFO - Running <TaskInstance: formula1-etl-pipeline.transform.transform_dim_status scheduled__2025-04-01T00:00:00+00:00 [running]> on host 38a05d0acc45
[2025-04-08T10:10:11.733+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='formula1-etl-pipeline' AIRFLOW_CTX_TASK_ID='transform.transform_dim_status' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-01T00:00:00+00:00'
[2025-04-08T10:10:11.734+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-08T10:10:11.769+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-08T10:10:11.780+0000] {logging_mixin.py:188} INFO - Đã tạo bảng thành công.
[2025-04-08T10:10:11.794+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-08T10:10:11.828+0000] {logging_mixin.py:188} INFO - Đã transform và lưu dữ liệu vào bảng.
[2025-04-08T10:10:11.829+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-08T10:10:11.830+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-08T10:10:11.841+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=formula1-etl-pipeline, task_id=transform.transform_dim_status, run_id=scheduled__2025-04-01T00:00:00+00:00, execution_date=20250401T000000, start_date=20250408T101011, end_date=20250408T101011
[2025-04-08T10:10:11.867+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-08T10:10:11.890+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-08T10:10:11.892+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
